db:
  repository: public.ecr.aws/v3g6g4v7/chaeeun0311-lab2
  tag: db-v1
  replicas: 1

redis:
  repository: public.ecr.aws/v3g6g4v7/chaeeun0311-lab2
  tag: redis-v1
  replicas: 1

app:
  repository: public.ecr.aws/v3g6g4v7/chaeeun0311-lab2
  tag: teacher-commit
  replicas: 1

nginx:
  repository: nginx
  tag: latest
  replicas: 1


ingress:
  healthCheckPath: /healthz
  host: www.chaeeun.shop
  certificateArn: arn:aws:acm:us-east-2:556683426101:certificate/37ba588a-fddf-4484-9a71-c2f453ede2da 
  group:
    name: shared-alb
    order: "10"
